const String FONT_FAMILY = 'NanumSquare';
const String LIGHT_MODE = 'light';
const String DARK_MODE = 'dark';
const String SYSTEM_MODE = 'system';

const String URL_VIEW = 'http://openapi.elevator.go.kr/openapi/service/ElevatorInformationService/getElevatorView?ServiceKey=';
const String URL_LIST = 'http://openapi.elevator.go.kr/openapi/service/ElevatorInformationService/getElevatorList?ServiceKey=';
const String KEY = 'Gs5DfSUBnVmIYae2tg%2FH7bl%2B8tWJr%2BO6c%2BeWWBhmJkzzBGxGo2%2FblgoF9rcBHVUR9kUq5R%2BQm%2FO04zN06%2BDW5Q%3D%3D';
const String NUMBER = '&_type=json&elevator_no=';

const String URL_INSPECT = 'http://openapi.elevator.go.kr/openapi/service/ElevatorInformationService/getElvtrInspctInqire?ServiceKey=$KEY';


const List<String> PARAMS = [
  "elevatorNo",
  "elvtrDivNm",
  "elvtrKindNm",
  "manufacturerName",
  "manufacturerTelno",
  "mnfcturCpnyCd",
  "elvtrFormNm",
  "ratedSpeed",
  "address1",
  "address2",
  "buldNm",
  "areaNo",
  "sigunguCd",
  "zipCd1",
  "zipCd2",
  "buldMgtNo1",
  "buldMgtNo2",
  "buldPrpos",
  "installationPlace",
  "elvtrAsignNo",
  "divGroundFloorCnt",
  "divUndgrndFloorCnt",
  "shuttleSection",
  "elvtrModel",
  "standardKey",
  "elvtrMgtNo1",
  "elvtrMgtNo2",
  "elvtrStts",
  "applcBeDt",
  "applcEnDt",
  "frstInstallationDe",
  "installationDe",
  "liveLoad",
  "ratedCap",
  "lastInspctDe",
  "lastInspctKind",
  "lastResultNm",
  "inspctInstt",
  "mntCpnyNm",
  "mntCpnyTelno",
  "mntCpnyCd",
  "partcpntNm",
  "partcpntTelno",
  "shuttleMngrNm",
  "shuttleMngrTelno",
];

const List<String> TITLES = [
  "승강기 번호",
  "구분",
  "종류",
  "제조업체",
  "제조업체연락처",
  "제조업체코드",
  "형식",
  "속력",
  "소재지1",
  "소재지2",
  "건물명",
  "지역번호",
  "시/군/구 코드",
  "우편번호1",
  "우편번호2",
  "건물관리번호1",
  "건물관리번호2",
  "건물용도",
  "설치장소",
  "호기",
  "건물최상층",
  "건물최하층",
  "운행구간",
  "모델명",
  "표준키번호",
  "승강기관리번호1",
  "승강기관리번호2",
  "상태",
  "운행유효기간(시작일)",
  "운행유효기간(종료일)",
  "최초설치일자",
  "설치일자",
  "적재하중",
  "정원",
  "최종검사일",
  "최종검사종류",
  "최종검사결과",
  "최종검사기관",
  "보수업체명",
  "보수업체연락처",
  "보수업체코드",
  "관리주체명",
  "관리주체연락처",
  "운행관리자SN",
  "운행관리자연락처"
];